### ISSUE TITLE
회원 가입 구현

### ISSUE THREAD

**Issue by SOHEELEE408** [f-lab-edu/gwangya-ticket#2]
- [x] 요구 사항 정리
- 이메일은 필수이다.
- 이메일은 이메일 형식을 만족해야 한다.
- 중복된 이메일은 사용할 수 없다.
- 비밀번호는 필수이다.
- 비밀번호는 알파벳 대소문자, 숫자, 특수 문자를 포함하여 8~20자리여야 한다. 
- 비밀번호는 암호화하여 저장되어야 한다. 

- [x] 테스트 구현
- [x] 프로덕션 코드 구현

**Comment by f-lab-maverick** [comment]
비밀번호 어떻게 관리할 것인가
- 해시(sha)의 문제 => 레인보우 테이블 이슈 어떻게 해결할 것인가?
- 소금, 후추를 뿌리면 됨
- 개인정보 어떻게 관리할 것인가
- 회원탈퇴할때 개인정보 다 지워야 함.
- 휴면계정 처리는? 고려해보자
