### ISSUE TITLE
공연 조회 API 구현

### ISSUE THREAD

**Issue by SOHEELEE408** [f-lab-edu/gwangya-ticket#3]
- 오늘 자 기준 오픈 된 공연, 오픈 예정인 공연 목록을 볼 수 있다.
- 로그인 없이 조회 가능하다.
- 목록에 표시된 공연은 모두 상세 조회 가능하다.

**Comment by f-lab-maverick** [comment]
부하를 최소화해야 합니다.
- Lock 최소화
- 성능 최적화
- DB 트랜잭션 최소화
